### ISSUE TITLE
(running - elapsed hh:mm:ss) 

### ISSUE THREAD

**Issue by lsawade** [icui/nnodes#15]
Hi,

If the job is aborted (e.g. time ran out in a job script).

```bash
nnlog
```

will return the elapsed time from node-start to execution of `nnlog` so it is not meaningful. Not sure how to tackle...

**Comment by lsawade** [comment]
can be close?

**Comment by icui** [comment]
The current solution does not work with a very long task in the main process, still needs improvement.

**Comment by lsawade** [comment]
Can confirm this. The jobs return and the workflow continues but they still show up as running with `nnlog`.
